run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    # Core linters - keeping only essential ones for now
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - typecheck
    # Formatting
    - gofmt
    - goimports
    # Note: errcheck, revive, gosec and other strict linters
    # will be enabled once existing issues are fixed in follow-up PRs

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - buildtag
      - composites
      - copylocks
      - lostcancel
      - nilfunc
      - printf
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/giantswarm/mcp-oauth
  
  misspell:
    locale: US
  
  gosec:
    excludes:
      - G104
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: comment-spacings

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst
    
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec
      path: _test\.go
  
  max-issues-per-linter: 0
  max-same-issues: 0
