version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosimple
    - typecheck
    - gosec
    - gocritic
    - revive
    - exhaustive
    - goconst
    - gocyclo
    - nestif
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - copyloopvar
    - dupl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    
    gofmt:
      simplify: true
    
    goimports:
      local-prefixes: github.com/giantswarm/mcp-oauth
    
    misspell:
      locale: US
    
    gosec:
      excludes:
        - G104
    
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    
    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
        - name: comment-spacings
    
    gocyclo:
      min-complexity: 15
    
    nestif:
      min-complexity: 5
  exclusions:
    rules:
      - linters:
          - gocyclo
          - errcheck
          - gosec
          - goconst
        path: _test\.go
      
      - linters:
          - gosec
        text: "G404: Use of weak random number generator"
        path: _test\.go

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
