run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosimple
    - typecheck
    - gosec
    - gocritic
    - revive
    - exhaustive
    - goconst
    - gocyclo
    - nestif
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - copyloopvar
    - dupl
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/giantswarm/mcp-oauth
  
  misspell:
    locale: US
  
  gosec:
    excludes:
      - G104
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: comment-spacings
  
  gocyclo:
    min-complexity: 15
  
  nestif:
    min-complexity: 5

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst
    
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec
      path: _test\.go
  
  max-issues-per-linter: 0
  max-same-issues: 0
