run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
    - revive
    - stylecheck
    - exhaustive
    - exportloopref
    - goconst
    - gocyclo
    - nestif
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/giantswarm/mcp-oauth
  
  misspell:
    locale: US
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (we handle this with errcheck)
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
  
  gocyclo:
    min-complexity: 15
  
  nestif:
    min-complexity: 5

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst
    
    # Exclude known issues
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec
      path: _test\.go
  
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

