name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: giantswarm/github-workflows/.github/workflows/release.yaml@main
    secrets:
      TAYLORBOT_GITHUB_ACTION: ${{ secrets.TAYLORBOT_GITHUB_ACTION }}
